Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using DMCTimesheet.Models;

namespace DMCTimesheet.Controllers
{
    public class SettingController : Controller
    {
        private readonly dmcDbcontext db = new dmcDbcontext();

        #region 1- WorkType - workgroup
        /// <summary>
        /// Danh sách worktype
        /// </summary>
        /// <returns></returns>
        public ActionResult Worktype()
        {
            //db.Database.Connection.ConnectionString = conn;
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            ViewBag.WorkGroup = db.C19_Workgroup.ToList();
            ViewBag.Details = db.C21_DetailAction.ToList();
            return View(db.C07_WorkType.ToList());
        }

        /// <summary>
        /// Tạo mới worktype
        /// </summary>
        /// <param name="WorkName"></param>
        /// <param name="WorkGroup"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateWorktype(string WorkName, int GroupId)
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            try
            {
                C07_WorkType ExistingName = db.C07_WorkType.FirstOrDefault(s => s.WorkName == WorkName);
                if (string.IsNullOrEmpty(WorkName) || GroupId <= 0 || ExistingName != null)
                {
                    ViewBag.SaveContent = $"Phải có tên nhóm hoặc tên nhóm đã có trong database";
                    ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                    ViewBag.Details = db.C21_DetailAction.ToList();
                    return View("WorkType", db.C07_WorkType.ToList());
                }
                if (ModelState.IsValid)
                {
                    C07_WorkType item = new C07_WorkType()
                    {
                        WorkName = WorkName,
                        GroupId = GroupId
                    };
                    db.C07_WorkType.Add(item);
                    db.SaveChanges();
                }
                ViewBag.SaveContent = "Add new worktype success";
                return RedirectToAction("Worktype");
            }
            catch (Exception ex)
            {
                ViewBag.SaveContent = $"Có lỗi trong quá trình lưu data trên server do {ex.InnerException.Message}";
                ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                ViewBag.Details = db.C21_DetailAction.ToList();
                return View("Worktype", db.C07_WorkType.ToList());
            }
        }

        [HttpGet]
        public ActionResult EditWorktype(int? Id)
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            if (Id == null) return RedirectToAction("WorkType");
            C07_WorkType enity = db.C07_WorkType.FirstOrDefault(s => s.ID == Id);
            if (enity == null)
            {
                ViewBag.SaveContent = "Không tìm thấy Worktype này";
                ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                ViewBag.Details = db.C21_DetailAction.ToList();
                return View(db.C07_WorkType.ToList());
            }
            ViewBag.WorkGroup = db.C19_Workgroup.ToList();
            ViewBag.Details = db.C21_DetailAction.ToList();
            return View(enity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditWorktype(int? Id, string WorkName, int? GroupId)
        {
            try
            {
                if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
                if (ModelState.IsValid)
                {
                    C07_WorkType item = db.C07_WorkType.FirstOrDefault(s => s.ID == Id);
                    if (item == null)
                    {
                        ViewBag.SaveContent = "Không tìm thấy Worktype này";
                        ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                        ViewBag.Details = db.C21_DetailAction.ToList();
                        return View(db.C07_WorkType.ToList());
                    }
                    item.WorkName = WorkName;
                    item.GroupId = (int)GroupId;
                    db.Entry(item).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Worktype");
            }
            catch (Exception ex)
            {
                ViewBag.SaveContent = $"Có lỗi trong quá trình Cập nhật do {ex.Message}";
                ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                ViewBag.Details = db.C21_DetailAction.ToList();
                return View(db.C07_WorkType.ToList());
            }
        }

        /// <summary>
        /// Page hiển thị thông tin Xóa
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult DeleteWorktype(int? id)
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            C07_WorkType enity = db.C07_WorkType.Where(s => s.ID == id).FirstOrDefault();
            if (enity == null)
            {
                ViewBag.SaveContent = "Không tìm thấy Worktype này";
                ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                ViewBag.Details = db.C21_DetailAction.ToList();
                return View(db.C07_WorkType.ToList());
            }
            ViewBag.WorkGroup = db.C19_Workgroup.ToList();
            ViewBag.Details = db.C21_DetailAction.ToList();
            return View(enity);
        }

        [HttpPost, ActionName("DeleteWorktype")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteWorktype(int Id)
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            try
            {
                C07_WorkType enity = db.C07_WorkType.Where(s => s.ID == Id).FirstOrDefault();
                if (enity == null)
                {
                    ViewBag.SaveContent = "Không tìm thấy Worktype này";
                    ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                    ViewBag.Details = db.C21_DetailAction.ToList();
                    return View(db.C07_WorkType.ToList());
                }
                db.C07_WorkType.Remove(enity);
                db.SaveChanges();
                //ViewBag.SaveContent = "Xóa thành công";
                return RedirectToAction("Worktype");
            }
            catch (Exception ex)
            {
                ViewBag.SaveContent = $"Xóa lỗi do {ex.Message}";
                ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                ViewBag.Details = db.C21_DetailAction.ToList();
                return View(db.C07_WorkType.ToList());
            }

        }

        #endregion

        #region 1A-WORKGROUP - Nhóm công việc

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateWorkGroup(string GroupName, int? MaNhom)
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            C19_Workgroup ExistingName = db.C19_Workgroup.FirstOrDefault(s => s.GroupName.Contains(GroupName) || s.MaNhom == MaNhom);
            if (string.IsNullOrEmpty(GroupName) || ExistingName != null)
            {
                ViewBag.SaveContent = $"Không bỏ trống tên nhóm hoặc Tên nhóm đã có trong database";
                ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                ViewBag.Details = db.C21_DetailAction.ToList();
                return View(db.C07_WorkType.ToList());
            }
            try
            {
                C19_Workgroup newEnity = new C19_Workgroup() { GroupName = GroupName.Trim(), MaNhom = (int)MaNhom };
                db.C19_Workgroup.Add(newEnity);
                db.SaveChanges();
                ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                ViewBag.Details = db.C21_DetailAction.ToList();
                return RedirectToAction("Worktype");
            }
            catch (Exception ex)
            {
                ViewBag.SaveContent = $"Tạo mới bị lỗi do {ex.Message}";
                ViewBag.WorkGroup = db.C19_Workgroup.ToList();
                ViewBag.Details = db.C21_DetailAction.ToList();
                return View(db.C07_WorkType.ToList());
            }
        }

        public ActionResult EditWorkGroup(int? Id)
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            if (Id == null) return RedirectToAction("Worktype");
            C19_Workgroup enity = db.C19_Workgroup.FirstOrDefault(s => s.GroupId == Id);
            if (enity == null) return RedirectToAction("Worktype");
            return View(enity);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditWorkGroup(int? Id, string GroupName, int? MaNhom)
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            if (Id == null || string.IsNullOrEmpty(GroupName)) return RedirectToAction("WorkType");
            C19_Workgroup enity = db.C19_Workgroup.FirstOrDefault(s => s.GroupId == Id);
            if (enity == null) return RedirectToAction("Worktype");
            try
            {
                enity.GroupName = GroupName;
                enity.MaNhom = MaNhom;
                db.Entry(enity).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Worktype");
            }
            catch (Exception ex)
            {
                ViewBag.SaveContent = $"Cập nhật bị lỗi do {ex.Message}";
                ViewBag.WorkGroup = db.C19_Workgroup.ToList();

Views/Setting/DeleteLocation.cshtml
@model DMCTimesheet.Models.C11_Location
@{
    ViewBag.Title = "Location Delete Page";
}
<h3>@ViewBag.Title</h3>
<div class="modal-body">
    @using (Html.BeginForm("DeleteLocationConfirmed", "Setting", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <form>
            @* WorkType *@
            <div class="form-group row text-left text-dark">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Id</lable>
                <input type="number" class="form-control col-md-7 col-sm-9 col-xs-9" name="LocationId" readonly required="" value="@Model.LocationId" />
            </div>
            <div class="form-group row text-left text-dark">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Tên địa điểm</lable>
                <input type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="LocationName" placeholder="Tên địa điểm" required="" value="@Model.LocationName" />
            </div>

            <br />
            <div class="clearfix"></div>

            <div class="form-group text-left">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3 text-left"></lable>
                <input type="submit" value="Xóa địa điểm" class="btn btn-success col-md-2" />
            </div>
        </form>
    }
</div>
<hr />
<h6 class="text-danger">@ViewBag.Error</h6>

Views/Setting/DeleteService.cshtml
@model DMCTimesheet.Models.C14_Services
@{
    ViewBag.Title = "Delete Service Page";
    List<DMCTimesheet.Models.C22_ServiceGroup> ServiceGroups = ViewBag.ServiceGroups as List<DMCTimesheet.Models.C22_ServiceGroup>;
}

<h3>@ViewBag.Title</h3>
<div class="modal-body">
    @using (Html.BeginForm("DeleteServiceConfirmed", "Setting", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <form>
            @* WorkType *@
            <div class="form-group row text-left text-dark">
                <lable hidden class="control-label col-md-3 col-sm-3 col-xs-3">Id</lable>
                <input hidden type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="ServiceId" value="@Model.ServiceId" />
            </div>
            <div class="form-group row text-left text-dark">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Tên dịch vụ</lable>
                <input readonly type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="ServiceName" required="" value="@Model.ServiceName" />
            </div>
            <div class="form-group row text-left text-dark">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Tên Nhóm dịch vụ</lable>
                <input readonly type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="" required="" value="@ServiceGroups.FirstOrDefault(s=>s.Id == Model.ServiceGroupId).ServiceGroupName" />
            </div>
            <br />
            <div class="clearfix"></div>

            <div class="form-group text-left">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3 text-left"></lable>
                <input type="submit" value="Xóa dịch vụ" class="btn btn-danger col-md-2" />
            </div>
        </form>
    }
</div>
<hr />
<h6 class="text-danger">@ViewBag.Error</h6>

Views/Setting/DeleteStatus.cshtml
@model DMCTimesheet.Models.C16_Status
@{
    ViewBag.Title = "Edit Project status Page";
}

<div class="modal-body">
    @using (Html.BeginForm("DeleteStatusConfirm", "Setting", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <form>
            @* WorkType *@

            <div class="form-group row text-left text-dark">
                <lable hidden class="control-label col-md-3 col-sm-3 col-xs-3">Id</lable>
                <input hidden type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="Id" placeholder="Tên" required="" value="@Model.Id" />
            </div>

            <div class="form-group row text-left text-dark">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Tên Tình trạng dự án</lable>
                <input type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="StatusName" placeholder="Tên" required="" value="@Model.StatusName" />
                <span class="@Model.ColorCode">@Model.StatusName</span>
            </div>

            <!--<div class="form-group row text-left text-dark inline">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Thay đổi Màu sắc</lable>
                <select name="ColorCode" class="form-control col-md-7 col-sm-9 col-xs-9" id="colorCodeSelected" onclick="OnchangeColor()">
                    <option id="@Model.ColorCode" value="@Model.ColorCode"></option>-->
            @*<option id="badge badge-primary" value="badge badge-primary" class="p-3 mb-2 bg-primary text-white">blue</option>
                <option id="badge badge-secondary" value="badge badge-secondary" class="p-3 mb-2 bg-secondary text-white">gray</option>
                <option id="badge badge-success" value="badge badge-success" class="p-3 mb-2 bg-success text-white">green</option>
                <option id="badge badge-danger" value="badge badge-danger" class="p-3 mb-2 bg-danger text-white">red</option>
                <option id="badge badge-warning" value="badge badge-warning" class="p-3 mb-2 bg-warning text-dark">orgrance</option>
                <option id="badge badge-info" value="badge badge-info" class="p-3 mb-2 bg-info text-white">cyan</option>
                <option id="badge badge-light" value="badge badge-light" class="p-3 mb-2 bg-light text-dark">white</option>
                <option id="badge badge-dark" value="badge badge-dark" class="p-3 mb-2 bg-dark text-white">black</option>*@
            <!--</select>-->
            @*<span id="review" class=""></span>*@
            <!--</div>-->

            <br />
            <div class="clearfix"></div>
            <div class="form-group text-left">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3 text-left"></lable>
                <input type="submit" value="Xóa tình trạng" class="btn btn-danger col-md-7" />
            </div>
        </form>
    }
</div>

<hr />
<h6 class="text-danger">@ViewBag.Error</h6>

Views/Setting/DeleteWorkGroup.cshtml
@model DMCTimesheet.Models.C19_Workgroup
@{
    ViewBag.Title = "WorkGroup delete Page";
}
<h3>Xóa Workgroup - <b class="text-primary">@Model.MaNhom - @Model.GroupName</b></h3>
<div class="modal-body">
    @using (Html.BeginForm("DeleteWorkGroupConfirmed", "Setting", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <form>
            <div class="form-group row text-left">
                <lable hidden class="control-label col-md-3 col-sm-3 col-xs-3">Id</lable>
                <input type="number" class="form-control col-md-7 col-sm-9 col-xs-9" hidden readonly name="GroupId" value="@Model.GroupId" />
            </div>
            <div class="form-group row text-left">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Mã nhóm</lable>
                <input type="number" disabled class="form-control col-md-7 col-sm-9 col-xs-9" name="MaNhom" placeholder="" required="" value="@Model.MaNhom" />
            </div>
            <div class="form-group row text-left">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Tên Nhóm</lable>
                <input type="text" disabled class="form-control col-md-7 col-sm-9 col-xs-9" name="GroupName" placeholder="" required="" value="@Model.GroupName" />
            </div>
            <div class="form-group text-left">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3 text-left"></lable>
                <input type="submit" value="Xóa nhóm" class="btn btn-danger col-md-1" />
            </div>
        </form>
    }
</div>
<div class="modal-footer">
    <div>
        <p class="text-danger">@ViewBag.Error</p>
    </div>
    <div class="clearfix"></div>
</div>

Views/Setting/Desciplines.cshtml
@model IEnumerable<DMCTimesheet.Models.C18_Descipline>
@{
    ViewBag.Title = "Member Position Manage Page";
    int stt = 1;
}

<div class="row">
    <div class="col-md-10">
        <h3>
            DANH MỤC BỘ MÔN - <b>
                @if (Model == null)
                {
                    <b class="text-primary">0</b>}
                else
                {<b class="text-danger">@Model.Count()</b>}
            </b>
        </h3>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-danger btn-small text-right" data-toggle="modal" data-target="#form"><i class="fa fa-plus-circle"></i> Thêm Chuyên môn</button>
    </div>
</div>

@* Modal create new *@
<h3 class="text-danger">@ViewBag.Error</h3>

@* Form nhập liệu *@
<div id="form" class="modal fade" role="dialog">
    <div class="modal-dialog modal-m">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Thêm chuyên môn</h3>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("CreateNewDesciplines", "Setting", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <form>
                        @* WorkType *@
                        <div class="form-group row text-left text-dark">
                            <lable class="control-label col-md-3 col-sm-3 col-xs-3">Tên chuyên môn</lable>
                            <input type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="DesciplineName" placeholder="Tên chuyên môn" required="" value="" />
                        </div>
                        <div class="form-group row text-left text-dark">
                            <lable class="control-label col-md-3 col-sm-3 col-xs-3">Kích hoạt</lable>
                            <select name="Active" class="form-control col-md-7 col-sm-9 col-xs-9">
                                <option value="0"></option>
                                <option value="1">Kích hoạt</option>
                                <option value="0">Không kích hoạt</option>
                            </select>
                        </div>

                        <br />
                        <div class="clearfix"></div>

                        <div class="form-group text-left">
                            <lable class="control-label col-md-3 col-sm-3 col-xs-3 text-left"></lable>
                            <input type="submit" value="Lưu thông tin" class="btn btn-success col-md-7" />
                        </div>
                    </form>
                }
            </div>
            <div class="modal-footer">
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
@* End Form nhập liệu *@


<div>
    <p class="text-danger">@ViewBag.SaveContent</p>
</div>

@*Table area*@
<div class="table-responsive col-md-12">
    <table class="table table-borderless">
        <tr class="text-white" style="background-color:#000000">
            <td class="col-sm-1">STT</td>
            <td class="col-sm-2">Tên Chuyên môn</td>
            <td class="col-sm-1">Tình trạng kích hoạt</td>
            <td class="col-sm-1">#</td>
        </tr>
    </table>
</div>
<div class="table-responsive" style="height:900px">
    <table class="table table-striped table-bordered">
        <tbody class="">
            @if (Model == null || Model.Count() == 0)
            {
                <tr class="row">
                    <td class="col-sm-1">Chưa có thông tin</td>
                </tr>
            }
            else
            {
                foreach (var item in Model.OrderBy(s => s.DesciplineName))
                {
                    <tr class="row">
                        <td class="col-md-1 text-center">@stt</td>
                        <td class="col-sm-2">
                            @if (item.DesciplineName != null)
                            {
                                <b>@Html.ActionLink(item.DesciplineName, "EditDescipline", "Setting", new { Id = item.Id }, new { @class = "text-primary" })</b>
                                @*<b class="text-danger">@item.DesciplineName</b>*@
                            }
                        </td>
                        <td class="col-sm-1">
                            @if (item.Active != null)
                            {
                                if (item.Active == true)
                                {
                                    <b class="text-primary">Active</b>
                                }
                                else
                                {
                                    <b class="text-primary">Un-active</b>
                                }

                            }
                        </td>
                        @* Button *@
                        <td class="col-md-1">
                            @Html.ActionLink(" ", "EditDescipline", "Setting", new { Id = item.Id }, new { @class = "fa fa-edit" })
                            @Html.ActionLink(" ", "DeleteDescipline", "Setting", new { Id = item.Id }, new { @class = "fa fa-remove btn" })
                        </td>
                    </tr>
                    stt++;
                }
            }
        </tbody>

    </table>

</div>

Views/Setting/EditCompanyService.cshtml
@model IEnumerable<DMCTimesheet.Models.C15_SubConServices>
@{
    ViewBag.Title = "Edit Subcontractor Service Page";
    //int stt = 1;
    List<DMCTimesheet.Models.C12_SubContractor> CompanyName = ViewBag.CompanyName as List<DMCTimesheet.Models.C12_SubContractor>;
    List<DMCTimesheet.Models.C14_Services> Service = ViewBag.Service as List<DMCTimesheet.Models.C14_Services>;
    List<DMCTimesheet.Models.C22_ServiceGroup> ServiceGroups = ViewBag.ServiceGroups as List<DMCTimesheet.Models.C22_ServiceGroup>;
    int SubconId = ViewBag.SubConId;
    DMCTimesheet.Models.C15_SubConServices SubConId = Model.FirstOrDefault(s=>s.SubConId == SubconId);

    int stt = 1;
}




<div class="modal-body">
    @using (Html.BeginForm("EditCompanyService", "Setting", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <form>
            <h3>@ViewBag.Title - <b class="text-danger">@CompanyName.FirstOrDefault(s => s.SubConId == SubconId).ShortName</b></h3>
            <div class="col-md-12">
                <table class="table table-borderless">
                    <thead>
                        <tr class="text-white row" style="background-color:#000000">
                            <td class="col-md-1">STT</td>
                            <td class="col-md-4">Tên dịch vụ</td>
                            <td class="col-md-4">Ngày tạo</td>
                            <td class="col-md-3">#</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="row">
                            <td class="" hidden>
                                <input hidden class="form-control" type="number" name="SubConId" value="@SubConId.SubConId" />                               
                            </td>
                            @foreach (var item in Model)
                            {
                                <td class="col-md-1">@stt</td>
                                <td class="form-group col-md-4">
                                    <select name="ServiceId" class="form-control">
                                        <option value="@item.ServiceId">@Service.FirstOrDefault(s => s.ServiceId == item.ServiceId).ServiceName</option>
                                        @foreach (var ser in Service.OrderBy(s => s.ServiceName))
                                        {
                                            <option value="@ser.ServiceId">@ser.ServiceName</option>
                                        }
                                    </select>
                                </td>
                                <td class="form-group col-md-4">
                                    <input type="date" class="form-control" name="Date" placeholder="" required="" value="@item.Date.Value.ToString("yyyy-MM-dd")" />
                                </td>

                                <td class="form-group col-md-3">
                                    <input type="submit" value="Lưu thông tin" class="btn btn-success" />
                                    <a>@Html.ActionLink("Xóa", "DeleteCompanyService", "Setting",new {Id = item.Id },new {@class = "btn btn-danger" })</a>
                                </td>
                                stt++;
                            }
                        </tr>
                    </tbody>
                </table>
            </div>            
            <hr />      
        </form>
    }
</div>
<hr />
<h6 class="text-danger">@ViewBag.Error</h6>

Views/Setting/EditJobSource.cshtml
@model DMCTimesheet.Models.C23_NguonViec
@{
    ViewBag.Title = "Edit Job source Page";
}

<h3>@ViewBag.Title</h3>
<div class="modal-body">
    @using (Html.BeginForm("EditJobSource", "Setting", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <form>
            @* WorkType *@
            <div class="form-group row text-left text-dark">
                <lable hidden class="control-label col-md-3 col-sm-3 col-xs-3">Id</lable>
                <input hidden type="number" class="form-control col-md-7 col-sm-9 col-xs-9" name="Id" placeholder="Id Nguồn việc" required="" value="@Model.Id" />
            </div>
            <div class="form-group row text-left text-dark">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Tên Nguồn việc</lable>
                <input type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="NguonViec" placeholder="Tên Nguồn việc" required="" value="@Model.NguonViec" />
            </div>
            <br />
            <div class="clearfix"></div>

            <div class="form-group text-left">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3 text-left"></lable>
                <input type="submit" value="Lưu thông tin cập nhật" class="btn btn-success col-md-3" />
            </div>
        </form>
    }
</div>
<hr />
<h6 class="text-danger">@ViewBag.Error</h6>

Views/Setting/EditProjectType.cshtml
@model DMCTimesheet.Models.C13_ProjectType
@{
    ViewBag.Title = "Project Type Edit Page";
}
<h3>@ViewBag.Title</h3>
<div class="modal-body">
    @using (Html.BeginForm("EditProjectType", "Setting", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <form>
            <div class="form-group row text-left text-dark">
                <lable hidden class="control-label col-md-3 col-sm-3 col-xs-3">Tên loại hình</lable>
                <input hidden type="number" class="form-control col-md-7 col-sm-9 col-xs-9" name="TypeId" placeholder="Tên loại hình" required="" value="@Model.TypeId" />
            </div>
            <div class="form-group row text-left text-dark">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Tên loại hình</lable>
                <input type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="TypeName" placeholder="Tên loại hình" required="" value="@Model.TypeName" />
            </div>
            <div class="form-group row text-left text-dark">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3">Chú thích</lable>
                <input type="text" class="form-control col-md-7 col-sm-9 col-xs-9" name="Description" placeholder="Chú thích" value="@Model.Description" />
            </div>


            <br />
            <div class="clearfix"></div>

            <div class="form-group text-left">
                <lable class="control-label col-md-3 col-sm-3 col-xs-3 text-left"></lable>
                <input type="submit" value="Lưu thông tin cập nhật" class="btn btn-success col-md-1" />
            </div>
        </form>
    }
</div>
<hr />
<h6 class="text-danger">@ViewBag.Error</h6>