Controllers/TimesheetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Dynamic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using DMCTimesheet.Models;
using Microsoft.Ajax.Utilities;

namespace DMCTimesheet.Controllers
{
    public class TimesheetController : Controller
    {

        private readonly dmcDbcontext db = new dmcDbcontext();
        //string conn = "server = 103.27.60.66; user id=dmcAdmin;password=DmcNewVision@2022#; persistsecurityinfo = True; database =cbimtech_dmc";

        #region General
        public ActionResult ProjectTimesheet()
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            //C02_Members logUser = Session["UserLogin"] as C02_Members;
            ViewBag.Projects = db.C01_Projects.ToList();
            ViewBag.Members = db.C02_Members.ToList();
            ViewBag.WorkType = db.C07_WorkType.ToList();
            ViewBag.Workgroup = db.C19_Workgroup.ToList();
            List<C08_Timesheet> ProjectTimesheet = db.C08_Timesheet.ToList();
            ViewBag.Embedstring = db.C98_EmbedString.OrderByDescending(s => s.Version).FirstOrDefault();
            return View(ProjectTimesheet);
        }

        public ActionResult TimesheetManage()
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            C02_Members logUser = Session["UserLogin"] as C02_Members;

            ViewBag.Members = db.C02_Members.Where(s => s.Deactived == false).ToList();
            ViewBag.Projects = db.C01_Projects.ToList();
            ViewBag.WorkType = db.C07_WorkType.ToList();
            ViewBag.Workgroup = db.C19_Workgroup.ToList();

            ViewBag.ProjectMember = GetDMCdata.DuAnTheoThanhVienID(logUser.UserID);


            List<string[]> group = new List<string[]>();    //Nhóm công việc theo workgroup
            List<string[]> listIdCV = new List<string[]>(); //List ID công việc để lọc
            foreach (var item in db.C07_WorkType.ToList())
            {
                string[] itm = new string[2];
                itm[0] = item.GroupId.ToString();
                itm[1] = item.WorkName;
                group.Add(itm);

                string[] idw = new string[2];
                idw[0] = item.ID.ToString();
                idw[1] = item.WorkName;
                listIdCV.Add(idw);
            }
            ViewBag.group = group;
            ViewBag.listIdCV = listIdCV;


            List<C08_Timesheet> mytimesheet = db.C08_Timesheet.Where(s => s.MemberID == logUser.UserID).ToList();

            //Công việc trong ngày
            List<DMCTimesheet.Models.C08_Timesheet> _ViecTrongNgay = new List<DMCTimesheet.Models.C08_Timesheet>();
            foreach (var item in mytimesheet)
            {
                if (DateTime.Today == DateTime.Parse(item.RecordDate.ToString())) _ViecTrongNgay.Add(item);
            }
            //Công việc trong tuần
            List<DMCTimesheet.Models.C08_Timesheet> _ViecTrongTuan = new List<DMCTimesheet.Models.C08_Timesheet>();

            var tuanhienhanh = CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(DateTime.Today, CalendarWeekRule.FirstFullWeek, DayOfWeek.Monday);
            int curYear = DateTime.Today.Year;
            int curMonth = DateTime.Today.Month;

            foreach (var item in mytimesheet)
            {
                DateTime itmDate = DateTime.Parse(item.RecordDate.ToString());
                int itmYear = DateTime.Parse(item.RecordDate.ToString()).Year;
                int itmMonth = DateTime.Parse(item.RecordDate.ToString()).Month;
                var tuanTS = CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(itmDate, CalendarWeekRule.FirstFullWeek, DayOfWeek.Monday);
                if (itmYear == curYear && itmMonth == curMonth & tuanTS == tuanhienhanh) _ViecTrongTuan.Add(item);
            }

            List<KeyValuePair<string, List<C08_Timesheet>>> TSbyYear = new List<KeyValuePair<string, List<C08_Timesheet>>>();
            List<KeyValuePair<string, List<C08_Timesheet>>> TSbyYear_Week = new List<KeyValuePair<string, List<C08_Timesheet>>>();

            //Lọc dữ liệu theo Năm và theo Tuần
            foreach (var item in mytimesheet.GroupBy(s => s.RecordDate.Value.Year))
            {
                KeyValuePair<string, List<C08_Timesheet>> tsY = new KeyValuePair<string, List<C08_Timesheet>>(item.Key.ToString(), item.ToList());
                TSbyYear.Add(tsY);//Timesheet theo năm
                var gp = item.ToList().GroupBy(s => new { weekName = GetIso8601WeekOfYear(s.RecordDate.Value) });

                foreach (var itm in gp)
                {
                    string WeekName = $"{item.Key}-W{itm.Key.weekName}";
                    KeyValuePair<string, List<C08_Timesheet>> tsYW = new KeyValuePair<string, List<C08_Timesheet>>(WeekName, itm.ToList<C08_Timesheet>());
                    TSbyYear_Week.Add(tsYW);
                }
            }


            //var _weeklyTS = mytimesheet.GroupBy(s=> new {_Year = s.RecordDate.Value.Year, _Week = GetIso8601WeekOfYear(s.RecordDate.Value) })
            //    .Select(p => new {_Year = p.Key._Year.ToString(), _Week = p.Key._Week.ToString(), ts = p.ToList() })
            //    .AsEnumerable().Select(s=>s.ToExpando());


            ViewBag.ViecTrongNgay = _ViecTrongNgay;
            ViewBag.ViecTrongTuan = _ViecTrongTuan;
            ViewBag.FullMyTimesheet = mytimesheet;
            ViewBag.YearlyTimesheet = TSbyYear;
            ViewBag.WeeklyTimesheet = TSbyYear_Week;

            ViewBag.Testjson = Json(TSbyYear, JsonRequestBehavior.AllowGet);

            //Detail actions
            ViewBag.DetailAction = db.C21_DetailAction.ToList();
            // List<string[]> worktypeId = new List<string[]>();    //Nhóm công việc theo workgroup
            List<string[]> listdetailaction = new List<string[]>(); //List ID công việc để lọc
            foreach (var item in db.C21_DetailAction.ToList())
            {
                string[] itm = new string[2];
                itm[0] = item.WorktypeId.ToString();
                itm[1] = item.DetailAction;
                listdetailaction.Add(itm);
            }
            ViewBag.actiondetailList = listdetailaction;
            return View(mytimesheet);
        }



        // Calculate ISO 8601 week of year
        public static int GetIso8601WeekOfYear(DateTime date)
        {
            // Calculate the week of the year using ISO 8601 definition
            // DayOfWeek day = CultureInfo.InvariantCulture.Calendar.GetDayOfWeek(date);
            return CultureInfo.InvariantCulture.Calendar.GetWeekOfYear(date, CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday);
        }


        public void GetData()
        {
            C02_Members logUser = Session["UserLogin"] as C02_Members;
            List<string[]> group = new List<string[]>();    //Nhóm công việc theo workgroup
            List<string[]> listIdCV = new List<string[]>(); //List ID công việc để lọc
            foreach (var item in db.C07_WorkType.ToList())
            {
                string[] itm = new string[2];
                itm[0] = item.GroupId.ToString();
                itm[1] = item.WorkName;
                group.Add(itm);

                string[] idw = new string[2];
                idw[0] = item.ID.ToString();
                idw[1] = item.WorkName;
                listIdCV.Add(idw);
            }
            ViewBag.group = group;
            ViewBag.listIdCV = listIdCV;


            List<C08_Timesheet> mytimesheet = db.C08_Timesheet.Where(s => s.MemberID == logUser.UserID).ToList();

            //Công việc trong ngày
            List<DMCTimesheet.Models.C08_Timesheet> _ViecTrongNgay = new List<DMCTimesheet.Models.C08_Timesheet>();
            foreach (var item in mytimesheet)
            {
                //int value = DateTime.Compare(DateTime.Parse(item.RecordDate.ToString()), DateTime.Today);
                if (DateTime.Today == DateTime.Parse(item.RecordDate.ToString()))
                {
                    _ViecTrongNgay.Add(item);
                }
            }
            //Công việc trong tuần
            List<DMCTimesheet.Models.C08_Timesheet> _ViecTrongTuan = new List<DMCTimesheet.Models.C08_Timesheet>();

            DateTime startDate = MakeDate(7, false);

            foreach (var item in mytimesheet)
            {
                int value = DateTime.Compare(DateTime.Parse(item.RecordDate.ToString()), startDate);
                if (value <= 7)
                {
                    _ViecTrongTuan.Add(item);
                }
            }
            ViewBag.ViecTrongNgay = _ViecTrongNgay;
            ViewBag.ViecTrongTuan = _ViecTrongTuan;
            ViewBag.DetailAction = db.C21_DetailAction.ToList();
        }

        public DateTime MakeDate(int duration, bool TinhToi)
        {
            int month = DateTime.Today.Month;
            int year = DateTime.Today.Year;
            int day = DateTime.Today.Day;

            int returnDate;

            if (TinhToi)
            {
                returnDate = day + duration;
            }
            else
            {
                int a = Math.Abs(day - duration);
                returnDate = a == 0 ? 1 : a;
            }
            return new DateTime(year, month, returnDate);
        }



        public ActionResult MemberTimesheet()
        {
            if (Session["UserLogin"] == null) return RedirectToAction("Login", "Home");
            C02_Members logUser = Session["UserLogin"] as C02_Members;

            ViewBag.Members = db.C02_Members.Where(s => s.Deactived == false).ToList();
            ViewBag.Projects = db.C01_Projects.ToList();
            ViewBag.WorkType = db.C07_WorkType.ToList();
            ViewBag.Workgroup = db.C19_Workgroup.ToList();

Views/Timesheet/Delete.cshtml
@model DMCTimesheet.Models.C08_Timesheet
@{
    ViewBag.Title = "Delete Timesheet";
    //Layout = "~/Views/Shared/_UserLayout.cshtml";
    List<DMCTimesheet.Models.C01_Projects> Projects = ViewBag.Projects as List<DMCTimesheet.Models.C01_Projects>;
    List<DMCTimesheet.Models.C07_WorkType> WorkType = ViewBag.WorkType as List<DMCTimesheet.Models.C07_WorkType>;
    string Error = "";
    Error = Session["Error"] as string;
}

<h2>@ViewBag.Title</h2>
<div class="nav navbar-fixed-top row">
    @Html.ActionLink(" Home", "UserPage", "Home", null, new { @class = "fa fa-home btn btn-round btn-dark" })
    @*@Html.ActionLink(" Interner List", "GetInternList", "ThucTapSinh", null, new { @class = "fa fa-plus-square-o btn btn-round btn-success" })*@
</div>

<div><i class="text-danger">@Error</i></div>

@using (Html.BeginForm("DeleteConfirmed", "Timesheet", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h3 class="text-center text-danger col-md-6">Bạn có chắc sẽ Xóa công việc này chứ?</h3>
        <br />
        <div class="clearfix"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row">
            <lable class="control-label col-md-2 text-left">Mã công việc</lable>
            <input type="text" class="form-control col-md-4 text-danger" readonly name="Id" placeholder="" required="" value="@Model.Id" />
        </div>
        @* Date *@
        <div class="form-group row">
            <lable class="control-label col-md-2 text-left">Ngày báo cáo</lable>
            <input type="date" class="form-control col-md-4" name="RecordDate" readonly value="@DateTime.Parse(Model.RecordDate.ToString()).ToString("yyyy-MM-dd")" />
        </div>

        @* ProjectTypeID *@
        <div class="form-group row  text-left">
            <lable class="control-label col-md-2 text-left"><b class="text-danger">Tên dự án</b></lable>
            <select name="ProjectId" class="form-control col-md-4">
                @if (Model.ProjectId != null)
                {
                    <option value=@Model.ProjectId>@Projects.FirstOrDefault(s => s.ProjectID == Model.ProjectId).ProjectName</option>

                }
            </select>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.WorkType, "Loại hình Công việc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-control col-md-4">
                <select name="WorkType" class="label col-md-12">
                    <option value="@Model.WorkType">@WorkType.FirstOrDefault(s => s.ID == Model.WorkType).WorkName</option>
                </select>
                @Html.ValidationMessageFor(model => model.WorkType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-md-2">Thời gian</label>
            <div class="col-md-6 control-group">
                <div class="form-group row">
                    <lable class="control-label col-md-2 text-left">Số giờ làm</lable>
                    <input type="number" class="form-control col-md-2" readonly name="Hour" value="@Model.Hour" />
                </div>
                <div class="form-group row">
                    <lable class="control-label col-md-2 text-left">Tăng ca (nếu có)</lable>
                    <input type="number" class="form-control col-md-2" readonly name="OT" value="@Model.OT" />
                </div>
            </div>
        </div>
        <div class="form-group row">
            <lable class="control-label col-md-2 text-left">Chú thích công việc</lable>
            <textarea class="form-control col-md-4" rows="3" name="Description" readonly>@Model.Description</textarea>
        </div>

        <div class="form-group row">
            <div class="col-md-offset-2 col-md-2">
                <input type="submit" value="Xóa công việc" class="btn btn-danger" />
            </div>
            <div class="text-danger">@ViewBag.WorkAlert</div>
        </div>
    </div>
}

Views/Timesheet/DeleteWorktype.cshtml
@model DMCTimesheet.Models.C07_WorkType
@{
    ViewBag.Title = "Cập nhật Worktype";
    //Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>@ViewBag.Title</h3>

<div class="nav navbar-fixed-top row">
    @Html.ActionLink(" Home", "Worktype", "Timesheet", null, new { @class = "fa fa-home btn btn-round btn-dark" })

</div>

<div class="modal-body">
    @using (Html.BeginForm("DeleteWorktype", "Timesheet", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <form>
            @* WorkType *@
            @Html.HiddenFor(model => model.ID)

            <div class="form-group row">
                @Html.LabelFor(model => model.WorkName, "Tên", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.WorkName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.WorkName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.WorkGroup, "Nhóm", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.WorkGroup, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.WorkGroup, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>

        </form>
    }
</div>
<div class="modal-footer">
    <div>
        <p class="text-danger">@ViewBag.SaveContent</p>
    </div>
    <div class="clearfix"></div>
</div>

Views/Timesheet/EditWorktype.cshtml
@model DMCTimesheet.Models.C07_WorkType
@{
    ViewBag.Title = "Cập nhật Worktype";
    //Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>@ViewBag.Title</h3>

<div class="nav navbar-fixed-top row">
    @Html.ActionLink(" Home", "Worktype", "Timesheet", null, new { @class = "fa fa-home btn btn-round btn-dark" })
   
</div>

<div class="modal-body">
    @using (Html.BeginForm("EditWorktype", "Timesheet", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
    <form>
        @* WorkType *@
        @Html.HiddenFor(model => model.ID)

        <div class="form-group row">
            @Html.LabelFor(model => model.WorkName, "Tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.WorkGroup, "Nhóm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkGroup, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />                
            </div>
        </div>

    </form>
    }
</div>
<div class="modal-footer">
    <div>
        <p class="text-danger">@ViewBag.SaveContent</p>
    </div>
    <div class="clearfix"></div>
</div>

Views/Timesheet/MemberTimesheet.cshtml
@model IEnumerable<DMCTimesheet.Models.C08_Timesheet>
@{
    DMCTimesheet.Models.C06_UserPermisRelationship Userpermiss = Session["UserPermission"] as DMCTimesheet.Models.C06_UserPermisRelationship;

    DMCTimesheet.Models.C02_Members loginUser = Session["UserLogin"] as DMCTimesheet.Models.C02_Members;
    int stt = 0;
    List<DMCTimesheet.Models.C02_Members> Members = ViewBag.Members as List<DMCTimesheet.Models.C02_Members>;
    List<DMCTimesheet.Models.C01_Projects> Projects = ViewBag.Projects as List<DMCTimesheet.Models.C01_Projects>;
    List<DMCTimesheet.Models.C07_WorkType> WorkTypes = ViewBag.WorkType as List<DMCTimesheet.Models.C07_WorkType>;
    List<DMCTimesheet.Models.C03_ProjectMembers> MyProjects = ViewBag.ProjectMember as List<DMCTimesheet.Models.C03_ProjectMembers>;
    List<DMCTimesheet.Models.C19_Workgroup> WorkGroup = ViewBag.Workgroup as List<DMCTimesheet.Models.C19_Workgroup>;

    //group data
    List<string[]> group = ViewBag.group as List<string[]>;    //Nhóm công việc theo workgroup
    List<string[]> listIdCV = ViewBag.listIdCV as List<string[]>; //List ID công việc để lọc
                                                                  //Công việc trong ngày
    List<DMCTimesheet.Models.C08_Timesheet> _ViecTrongNgay = ViewBag.ViecTrongNgay as List<DMCTimesheet.Models.C08_Timesheet>;
    //Công việc trong tuần
    List<DMCTimesheet.Models.C08_Timesheet> _ViecTrongTuan = ViewBag.ViecTrongTuan as List<DMCTimesheet.Models.C08_Timesheet>;

}
<h1>MEMBER TIMESHEET</h1>

Views/Timesheet/ProjectTimesheet.cshtml
@model IEnumerable<DMCTimesheet.Models.C08_Timesheet>
@{
    DMCTimesheet.Models.C06_UserPermisRelationship Userpermiss = Session["UserPermission"] as DMCTimesheet.Models.C06_UserPermisRelationship;
    DMCTimesheet.Models.C02_Members loginUser = Session["UserLogin"] as DMCTimesheet.Models.C02_Members;

    List<DMCTimesheet.Models.C01_Projects> Projects = ViewBag.Projects as List<DMCTimesheet.Models.C01_Projects>;
    List<DMCTimesheet.Models.C02_Members> Members = ViewBag.Members as List<DMCTimesheet.Models.C02_Members>;
    List<DMCTimesheet.Models.C07_WorkType> WorkType = ViewBag.WorkType as List<DMCTimesheet.Models.C07_WorkType>;
    List<DMCTimesheet.Models.C19_Workgroup> WorkGroup = ViewBag.Workgroup as List<DMCTimesheet.Models.C19_Workgroup>;
    //string BI_embed = "https://app.powerbi.com/view?r=eyJrIjoiMWFhYTViM2ItYjYxNi00ZGI5LTk1MjQtNGUzZTc0NjdkZGIxIiwidCI6ImFmYzIxMzc5LTEwMGItNDYzZC04MzI1LWNkMTY4NmFlOTRjYSIsImMiOjEwfQ%3D%3D";
    DMCTimesheet.Models.C98_EmbedString BI_embed = ViewBag.Embedstring as DMCTimesheet.Models.C98_EmbedString;

    int stt = 1;
}

<h3>@ViewBag.Title</h3>
<div>
    <h4>BI Report</h4>
    <div>
        <div class="embed-responsive embed-responsive-16by9">
            @*<iframe title="DMCreport - Page 1" width="1024" height="1060" src="https://app.powerbi.com/view?r=eyJrIjoiMWFhYTViM2ItYjYxNi00ZGI5LTk1MjQtNGUzZTc0NjdkZGIxIiwidCI6ImFmYzIxMzc5LTEwMGItNDYzZC04MzI1LWNkMTY4NmFlOTRjYSIsImMiOjEwfQ%3D%3D" frameborder="0" allowFullScreen="true"></iframe>*@
            <iframe title="DMCreport - Page 1" width="1024" height="1060" src=@BI_embed.EmbedString frameborder="0" allowFullScreen="true"></iframe>
        </div>
    </div>
</div>

<div>
    <h4>DANH MỤC TIMESHEET THEO DỰ ÁN</h4>
    <div>
        <table class="table">
            <thead class="table-dark">
                <tr class="row text-white">
                    <td class="col-md-1">STT</td>
                    <td class="col-md-1">Tên dự án</td>
                    <td class="col-md-1">Ngày</td>
                    <td class="col-md-2">Tên Thành viên</td>
                    <td class="col-md-2">Công việc</td>
                    <td class="col-md-1">Thời gian thực hiện</td>
                    <td class="col-md-3">Chi tiết công việc</td>
                </tr>
            </thead>
        </table>
    </div>
    <div class="table-responsive" style="height:800px">
        <table class="table table-bordered table-striped">
           <caption></caption>
            <tbody>
                @if (Model == null || Model.Count() == 0)
                {
                    <tr>
                        <td class="row text-white">Chưa có timesheet</td>
                    </tr>
                }
                else
                {
                    foreach (var item in Model.OrderByDescending(s=>s.RecordDate))
                    {
                        <tr class="row">
                            <td class="col-md-1 text-center text-dark">@stt</td>
                            <td class="col-md-1">
                                @if (item.ProjectId != null)
                                {
                                    @*<b class="text-primary">@Projects.FirstOrDefault(s => s.ProjectID == item.ProjectId).ProjectOtherName</b>*@
                                <b>@Html.ActionLink(Projects.FirstOrDefault(s => s.ProjectID == item.ProjectId).ProjectOtherName, "UserEdit", "Timesheet", new { id = item.Id }, new { @class = "text-primary" })</b>
                                }
                                else
                                {
                                    @*<b class="text-danger">Công việc chung</b>*@
                            <b>@Html.ActionLink("Công việc chung", "UserEdit", "Timesheet", new { id = item.Id }, new { @class = "text-primary" })</b>
                                }
                            </td>
                            <td class="col-md-1 text-center text-dark">
                                @if (item.RecordDate != null)
                                {
                                    @DateTime.Parse(item.RecordDate.ToString()).ToString("yyyy-MM-dd");
                                }
                            </td>
                            <td class="col-md-2">
                                @if (item.MemberID != null)
                                {
                                    <b class="text-danger">@Members.FirstOrDefault(s => s.UserID == item.MemberID).FullName</b>
                                }

                            </td>

                            <td class="col-md-2">
                                @if (item.WorkType != null)
                                {
                                    <a class="text-dark">@WorkType.FirstOrDefault(s => s.ID == item.WorkType).WorkName</a>
                                }
                            </td>

                            <td class="col-md-1">
                                @if (item.Hour != null || item.OT != null)
                                {
                                    <div class="inline">
                                        <p>Hour: <b class="text-primary">@item.Hour</b></p>
                                        <p>OT: <b class="text-danger">@item.OT</b></p>
                                    </div>
                                }
                            </td>
                            <td class="col-md-3 text-dark">
                                @if (item.Description != null)
                                {
                                    <i>@item.Description</i>
                                }
                            </td>
                        </tr>
                        stt++;
                    }
                }
            </tbody>
        </table>

    </div>
</div>

Views/Timesheet/_TimeSheetAjaxSearch.cshtml
@model IEnumerable<DMCTimesheet.Models.C08_Timesheet>
@{
    int stt = 0;
    List<DMCTimesheet.Models.C02_Members> Members = ViewBag.Members as List<DMCTimesheet.Models.C02_Members>;
    List<DMCTimesheet.Models.C01_Projects> Projects = ViewBag.Projects as List<DMCTimesheet.Models.C01_Projects>;
    DMCTimesheet.Models.C02_Members loginUser = Session["UserLogin"] as DMCTimesheet.Models.C02_Members;
}
@try
{
    foreach (var item in Model.Where(s=>s.MemberID == loginUser.UserID).GroupBy(s => s.ProjectId))
    {       
        <tr>
            <td colspan="8" class="text-left"><h5><b class="text-primary">@item.Key - @Projects.Where(s => s.ProjectID == item.Key).FirstOrDefault().ProjectName </b><i class="fa fa-bicycle text-danger"> @item.ToList().Count() records</i></h5></td>
            @*<td colspan="8" class="text-left"><h5><b class="text-primary">@Members.Where(s=>s.BIMstaffID == item.Key).FirstOrDefault().Sortname</b></h5></td>*@
        </tr>
        foreach (var itm in item.ToList())
        {
            stt++;
            <tr>
                <td>@stt</td>
                <td>@DateTime.Parse(itm.RecordDate.ToString()).ToShortDateString()</td>
                <td>@itm.ProjectId - @Projects.FirstOrDefault(s=>s.ProjectID == itm.ProjectId).ProjectName</td>
                <td>@itm.WorkType</td>
                <td>@itm.Hour</td>
                <td>@itm.OT</td>
                <td>@itm.Description</td>
                <td>
                    @Html.ActionLink(" ", "UserEdit", "Timesheet", new { id = itm.Id }, new { @class = "fa fa-edit btn" })
                    @Html.ActionLink(" ", "UserDelete", "Timesheet", new { id = itm.Id }, new { @class = " fa fa-remove btn" })
                </td>
            </tr>
        }

    }
}
catch (Exception)
{
    <h5>Không tìm thấy dữ liệu</h5>
}